// <auto-generated />
using System;
using AptekaCursovoy.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AptekaCursovoy.Migrations
{
    [DbContext(typeof(AptekaCursovoyContext))]
    partial class AptekaCursovoyContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AptekaCursovoy.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Адрес")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ДатаРождения")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Должность")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Зарплата")
                        .HasColumnType("int");

                    b.Property<string>("Имя")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Телефон")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Фамилия")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Фото")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Empoyee");
                });

            modelBuilder.Entity("AptekaCursovoy.Models.Tovar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ДатаПоступления")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Категория")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Количество")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Название")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Описание")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Поставщик")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Производитель")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Фото")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Цена")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tovar");
                });
#pragma warning restore 612, 618
        }
    }
}
